name: train-my-model
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
     runs-on: ubuntu-latest
     container: docker://dvcorg/cml-py3:latest
     steps:
        
        - name: cml_run
          uses: actions/checkout@v2
          env:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
        - run: |
              sudo apt-get update
              sudo apt-get install build-essential swig python3-dev
              curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install
              pip install -r requirements.txt
              pip install --upgrade plotly
              pip install pandas-profiling
              pip3 install -U scikit-learn
              python train_copy.py
              ls -lh
              cat metrics.txt >> report.md
              cml-publish *.png --md >> report.md
              cml-send-comment report.md