name: train-my-model
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
     runs-on: ubuntu-latest
     container: docker://dvcorg/cml-py3:latest
     steps:
        
        - name: cml_run
          uses: actions/checkout@v2
          env:
              repo_token: ${{ secrets.GITHUB_TOKEN }}
        - run: |
              curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install
              pip install cython
              sudo apt-get install build-essential python3 python3-dev swig
              pip install -U -r requirements.txt  --no-use-pep517 
              python train_copy.py

              cat metrics.txt >> report.md
              cml-publish *.png --md >> report.md
              cml-send-comment report.md